version: '3.8'

services:
  nginx:
    image: nginx:latest
    deploy:
      replicas: 3
      placement:
        constraints: [node.role != manager]
    volumes:
      - nginx_vol:/usr/share/nginx/html
    ports:
      - "8003:80"
    networks:
      - jjh_net
      
volumes:
  nginx_vol:
    driver: local
    driver_opts: 
      type: "nfs4"
      o: "addr=211.183.3.201,rw"
      device: ":/nginx"

networks:
  jjh_net:
    driver: overlay
    attachable: true
